# For use with 'Provisional_COVID-19_Death_Counts_by_Sex__Age__and_State.csv' dataset
# Analyzes statistical information of COVID-19 data including mean, median, mode,
# range, variance, quartiles, and standard deviation
#
# Alex Derby for Team Eva - CAP 4784 Data Analytics
#
# Age groups & Corresponding Rows
# 0-24 = [1:5]
# 25-44 = [6:9]
# 45-64 = [10:13]
# 65+ = [14:16]

import pandas as pd
import numpy as np
from scipy import stats

data = pd.read_csv('Provisional_COVID-19_Death_Counts_by_Sex__Age__and_State.csv')

# Get median
ag_0_24_covid_deaths_median = np.median(data.loc[1:5, 'COVID-19 Deaths'].values.tolist())
print('Median COVID-19 Deaths for Ages 0-24: ' + str(ag_0_24_covid_deaths_median))
ag_25_44_covid_deaths_median = np.median(data.loc[6:9, 'COVID-19 Deaths'].values.tolist())
print('Median COVID-19 Deaths for Ages 25-44: ' + str(ag_25_44_covid_deaths_median))
ag_45_64_covid_deaths_median = np.median(data.loc[10:13, 'COVID-19 Deaths'].values.tolist())
print('Median COVID-19 Deaths for Ages 45-64: ' + str(ag_45_64_covid_deaths_median))
ag_65_up_covid_deaths_median = np.median(data.loc[14:16, 'COVID-19 Deaths'].values.tolist())
print('Median COVID-19 Deaths for Ages 65 and up: ' + str(ag_65_up_covid_deaths_median))
print()
ag_0_24_pneumonia_deaths_median = np.median(data.loc[1:5, 'Pneumonia Deaths'].values.tolist())
print('Median Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_pneumonia_deaths_median))
ag_25_44_pneumonia_deaths_median = np.median(data.loc[6:9, 'Pneumonia Deaths'].values.tolist())
print('Median Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_pneumonia_deaths_median))
ag_45_64_pneumonia_deaths_median = np.median(data.loc[10:13, 'Pneumonia Deaths'].values.tolist())
print('Median Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_pneumonia_deaths_median))
ag_65_up_pneumonia_deaths_median = np.median(data.loc[14:16, 'Pneumonia Deaths'].values.tolist())
print('Median Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_pneumonia_deaths_median))
print()
ag_0_24_influenza_deaths_median = np.median(data.loc[1:5, 'Influenza Deaths'].values.tolist())
print('Median Influenza Deaths for Ages 0-24: ' + str(ag_0_24_influenza_deaths_median))
ag_25_44_influenza_deaths_median = np.median(data.loc[6:9, 'Influenza Deaths'].values.tolist())
print('Median Influenza Deaths for Ages 25-44: ' + str(ag_25_44_influenza_deaths_median))
ag_45_64_influenza_deaths_median = np.median(data.loc[10:13, 'Influenza Deaths'].values.tolist())
print('Median Influenza Deaths for Ages 45-64: ' + str(ag_45_64_influenza_deaths_median))
ag_65_up_influenza_deaths_median = np.median(data.loc[14:16, 'Influenza Deaths'].values.tolist())
print('Median Influenza Deaths for Ages 65 and up: ' + str(ag_65_up_influenza_deaths_median))
print()
ag_0_24_covid_and_pneumonia_deaths_median = np.median(data.loc[1:5, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Median COVID-19 & Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_covid_and_pneumonia_deaths_median))
ag_25_44_covid_and_pneumonia_deaths_median = np.median(data.loc[6:9, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Median COVID-19 & Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_covid_and_pneumonia_deaths_median))
ag_45_64_covid_and_pneumonia_deaths_median = np.median(data.loc[10:13, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Median COVID-19 & Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_covid_and_pneumonia_deaths_median))
ag_65_up_covid_and_pneumonia_deaths_median = np.median(data.loc[14:16, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Median COVID-19 & Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_covid_and_pneumonia_deaths_median))
print()

# Get mode
ag_0_24_covid_deaths_mode = stats.mode(data.loc[1:5, 'COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 Deaths for Ages 0-24: ' + str(ag_0_24_covid_deaths_mode))
ag_25_44_covid_deaths_mode = stats.mode(data.loc[6:9, 'COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 Deaths for Ages 25-44: ' + str(ag_25_44_covid_deaths_mode))
ag_45_64_covid_deaths_mode = stats.mode(data.loc[10:13, 'COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 Deaths for Ages 45-64: ' + str(ag_45_64_covid_deaths_mode))
ag_65_up_covid_deaths_mode = stats.mode(data.loc[14:16, 'COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 Deaths for Ages 65 and up: ' + str(ag_65_up_covid_deaths_mode))
print()
ag_0_24_pneumonia_deaths_mode = stats.mode(data.loc[1:5, 'Pneumonia Deaths'].values.tolist())
print('Mode Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_pneumonia_deaths_mode))
ag_25_44_pneumonia_deaths_mode = stats.mode(data.loc[6:9, 'Pneumonia Deaths'].values.tolist())
print('Mode Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_pneumonia_deaths_mode))
ag_45_64_pneumonia_deaths_mode = stats.mode(data.loc[10:13, 'Pneumonia Deaths'].values.tolist())
print('Mode Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_pneumonia_deaths_mode))
ag_65_up_pneumonia_deaths_mode = stats.mode(data.loc[14:16, 'Pneumonia Deaths'].values.tolist())
print('Mode Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_pneumonia_deaths_mode))
print()
ag_0_24_influenza_deaths_mode = stats.mode(data.loc[1:5, 'Influenza Deaths'].values.tolist())
print('Mode Influenza Deaths for Ages 0-24: ' + str(ag_0_24_influenza_deaths_mode))
ag_25_44_influenza_deaths_mode = stats.mode(data.loc[6:9, 'Influenza Deaths'].values.tolist())
print('Mode Influenza Deaths for Ages 25-44: ' + str(ag_25_44_influenza_deaths_mode))
ag_45_64_influenza_deaths_mode = stats.mode(data.loc[10:13, 'Influenza Deaths'].values.tolist())
print('Mode Influenza Deaths for Ages 45-64: ' + str(ag_45_64_influenza_deaths_mode))
ag_65_up_influenza_deaths_mode = stats.mode(data.loc[14:16, 'Influenza Deaths'].values.tolist())
print('Mode Influenza Deaths for Ages 65 and up: ' + str(ag_65_up_influenza_deaths_mode))
print()
ag_0_24_covid_and_pneumonia_deaths_mode = stats.mode(data.loc[1:5, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 & Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_covid_and_pneumonia_deaths_mode))
ag_25_44_covid_and_pneumonia_deaths_mode = stats.mode(data.loc[6:9, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 & Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_covid_and_pneumonia_deaths_mode))
ag_45_64_covid_and_pneumonia_deaths_mode = stats.mode(data.loc[10:13, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 & Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_covid_and_pneumonia_deaths_mode))
ag_65_up_covid_and_pneumonia_deaths_mode = stats.mode(data.loc[14:16, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mode COVID-19 & Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_covid_and_pneumonia_deaths_mode))

# Get Mean
ag_0_24_covid_deaths_mean = np.mean(data.loc[1:5, 'COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 Deaths for Ages 0-24: ' + str(ag_0_24_covid_deaths_mean))
ag_25_44_covid_deaths_mean = np.mean(data.loc[6:9, 'COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 Deaths for Ages 25-44: ' + str(ag_25_44_covid_deaths_mean))
ag_45_64_covid_deaths_mean = np.mean(data.loc[10:13, 'COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 Deaths for Ages 45-64: ' + str(ag_45_64_covid_deaths_mean))
ag_65_up_covid_deaths_mean = np.mean(data.loc[14:16, 'COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 Deaths for Ages 65 and up: ' + str(ag_65_up_covid_deaths_mean))
print()
ag_0_24_pneumonia_deaths_mean = np.mean(data.loc[1:5, 'Pneumonia Deaths'].values.tolist())
print('Mean Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_pneumonia_deaths_mean))
ag_25_44_pneumonia_deaths_mean = np.mean(data.loc[6:9, 'Pneumonia Deaths'].values.tolist())
print('Mean Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_pneumonia_deaths_mean))
ag_45_64_pneumonia_deaths_mean = np.mean(data.loc[10:13, 'Pneumonia Deaths'].values.tolist())
print('Mean Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_pneumonia_deaths_mean))
ag_65_up_pneumonia_deaths_mean = np.mean(data.loc[14:16, 'Pneumonia Deaths'].values.tolist())
print('Mean Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_pneumonia_deaths_mean))
print()
ag_0_24_influenza_deaths_mean = np.mean(data.loc[1:5, 'Influenza Deaths'].values.tolist())
print('Mean Influenza Deaths for Ages 0-24: ' + str(ag_0_24_influenza_deaths_mean))
ag_25_44_influenza_deaths_mean = np.mean(data.loc[6:9, 'Influenza Deaths'].values.tolist())
print('Mean Influenza Deaths for Ages 25-44: ' + str(ag_25_44_influenza_deaths_mean))
ag_45_64_influenza_deaths_mean = np.mean(data.loc[10:13, 'Influenza Deaths'].values.tolist())
print('Mean Influenza Deaths for Ages 45-64: ' + str(ag_45_64_influenza_deaths_mean))
ag_65_up_influenza_deaths_mean = np.mean(data.loc[14:16, 'Influenza Deaths'].values.tolist())
print('Mean Influenza Deaths for Ages 65 and up: ' + str(ag_65_up_influenza_deaths_mean))
print()
ag_0_24_covid_and_pneumonia_deaths_mean = np.mean(data.loc[1:5, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 & Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_covid_and_pneumonia_deaths_mean))
ag_25_44_covid_and_pneumonia_deaths_mean = np.mean(data.loc[6:9, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 & Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_covid_and_pneumonia_deaths_mean))
ag_45_64_covid_and_pneumonia_deaths_mean = np.mean(data.loc[10:13, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 & Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_covid_and_pneumonia_deaths_mean))
ag_65_up_covid_and_pneumonia_deaths_mean = np.mean(data.loc[14:16, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Mean COVID-19 & Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_covid_and_pneumonia_deaths_mean))
print()

# Get Range
ag_0_24_covid_deaths_ptp = np.ptp(data.loc[1:5, 'COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 Deaths for Ages 0-24: ' + str(ag_0_24_covid_deaths_ptp))
ag_25_44_covid_deaths_ptp = np.ptp(data.loc[6:9, 'COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 Deaths for Ages 25-44: ' + str(ag_25_44_covid_deaths_ptp))
ag_45_64_covid_deaths_ptp = np.ptp(data.loc[10:13, 'COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 Deaths for Ages 45-64: ' + str(ag_45_64_covid_deaths_ptp))
ag_65_up_covid_deaths_ptp = np.ptp(data.loc[14:16, 'COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 Deaths for Ages 65 and up: ' + str(ag_65_up_covid_deaths_ptp))
print()
ag_0_24_pneumonia_deaths_ptp = np.ptp(data.loc[1:5, 'Pneumonia Deaths'].values.tolist())
print('Range of Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_pneumonia_deaths_ptp))
ag_25_44_pneumonia_deaths_ptp = np.ptp(data.loc[6:9, 'Pneumonia Deaths'].values.tolist())
print('Range of Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_pneumonia_deaths_ptp))
ag_45_64_pneumonia_deaths_ptp = np.ptp(data.loc[10:13, 'Pneumonia Deaths'].values.tolist())
print('Range of Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_pneumonia_deaths_ptp))
ag_65_up_pneumonia_deaths_ptp = np.ptp(data.loc[14:16, 'Pneumonia Deaths'].values.tolist())
print('Range of Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_pneumonia_deaths_ptp))
print()
ag_0_24_influenza_deaths_ptp = np.ptp(data.loc[1:5, 'Influenza Deaths'].values.tolist())
print('Range of Influenza Deaths for Ages 0-24: ' + str(ag_0_24_influenza_deaths_ptp))
ag_25_44_influenza_deaths_ptp = np.ptp(data.loc[6:9, 'Influenza Deaths'].values.tolist())
print('Range of Influenza Deaths for Ages 25-44: ' + str(ag_25_44_influenza_deaths_ptp))
ag_45_64_influenza_deaths_ptp = np.ptp(data.loc[10:13, 'Influenza Deaths'].values.tolist())
print('Range of Influenza Deaths for Ages 45-64: ' + str(ag_45_64_influenza_deaths_ptp))
ag_65_up_influenza_deaths_ptp = np.ptp(data.loc[14:16, 'Influenza Deaths'].values.tolist())
print('Range of Influenza Deaths for Ages 65 and up: ' + str(ag_65_up_influenza_deaths_ptp))
print()
ag_0_24_covid_and_pneumonia_deaths_ptp = np.ptp(data.loc[1:5, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 & Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_covid_and_pneumonia_deaths_ptp))
ag_25_44_covid_and_pneumonia_deaths_ptp = np.ptp(data.loc[6:9, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 & Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_covid_and_pneumonia_deaths_ptp))
ag_45_64_covid_and_pneumonia_deaths_ptp = np.ptp(data.loc[10:13, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 & Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_covid_and_pneumonia_deaths_ptp))
ag_65_up_covid_and_pneumonia_deaths_ptp = np.ptp(data.loc[14:16, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Range of COVID-19 & Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_covid_and_pneumonia_deaths_ptp))
print()

# Get Vairance
ag_0_24_covid_deaths_variance = 0
ag_25_44_covid_deaths_variance = 0
ag_45_64_covid_deaths_variance = 0
ag_65_up_covid_deaths_variance = 0

# Get Quartiles
ag_0_24_covid_deaths_quartile1 = 0
ag_25_44_covid_deaths_quartile1 = 0
ag_45_64_covid_deaths_quartile1 = 0
ag_65_up_covid_deaths_quartile1 = 0

ag_0_24_covid_deaths_quartile3 = 0
ag_25_44_covid_deaths_quartile3 = 0
ag_45_64_covid_deaths_quartile3 = 0
ag_65_up_covid_deaths_quartile3 = 0

# Get Standard Deviation
ag_0_24_covid_deaths_std = np.std(data.loc[1:5, 'COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 Deaths for Ages 0-24: ' + str(ag_0_24_covid_deaths_std))
ag_25_44_covid_deaths_std = np.std(data.loc[6:9, 'COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 Deaths for Ages 25-44: ' + str(ag_25_44_covid_deaths_std))
ag_45_64_covid_deaths_std = np.std(data.loc[10:13, 'COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 Deaths for Ages 45-64: ' + str(ag_45_64_covid_deaths_std))
ag_65_up_covid_deaths_std = np.std(data.loc[14:16, 'COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 Deaths for Ages 65 and up: ' + str(ag_65_up_covid_deaths_std))
print()
ag_0_24_pneumonia_deaths_std = np.std(data.loc[1:5, 'Pneumonia Deaths'].values.tolist())
print('Standard Deviation Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_pneumonia_deaths_std))
ag_25_44_pneumonia_deaths_std = np.std(data.loc[6:9, 'Pneumonia Deaths'].values.tolist())
print('Standard Deviation Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_pneumonia_deaths_std))
ag_45_64_pneumonia_deaths_std = np.std(data.loc[10:13, 'Pneumonia Deaths'].values.tolist())
print('Standard Deviation Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_pneumonia_deaths_std))
ag_65_up_pneumonia_deaths_std = np.std(data.loc[14:16, 'Pneumonia Deaths'].values.tolist())
print('Standard Deviation Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_pneumonia_deaths_std))
print()
ag_0_24_influenza_deaths_std = np.std(data.loc[1:5, 'Influenza Deaths'].values.tolist())
print('Standard Deviation Influenza Deaths for Ages 0-24: ' + str(ag_0_24_influenza_deaths_std))
ag_25_44_influenza_deaths_std = np.std(data.loc[6:9, 'Influenza Deaths'].values.tolist())
print('Standard Deviation Influenza Deaths for Ages 25-44: ' + str(ag_25_44_influenza_deaths_std))
ag_45_64_influenza_deaths_std = np.std(data.loc[10:13, 'Influenza Deaths'].values.tolist())
print('Standard Deviation Influenza Deaths for Ages 45-64: ' + str(ag_45_64_influenza_deaths_std))
ag_65_up_influenza_deaths_std = np.std(data.loc[14:16, 'Influenza Deaths'].values.tolist())
print('Standard Deviation Influenza Deaths for Ages 65 and up: ' + str(ag_65_up_influenza_deaths_std))
print()
ag_0_24_covid_and_pneumonia_deaths_std = np.std(data.loc[1:5, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 & Pneumonia Deaths for Ages 0-24: ' + str(ag_0_24_covid_and_pneumonia_deaths_std))
ag_25_44_covid_and_pneumonia_deaths_std = np.std(data.loc[6:9, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 & Pneumonia Deaths for Ages 25-44: ' + str(ag_25_44_covid_and_pneumonia_deaths_std))
ag_45_64_covid_and_pneumonia_deaths_std = np.std(data.loc[10:13, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 & Pneumonia Deaths for Ages 45-64: ' + str(ag_45_64_covid_and_pneumonia_deaths_std))
ag_65_up_covid_and_pneumonia_deaths_std = np.std(data.loc[14:16, 'Pneumonia and COVID-19 Deaths'].values.tolist())
print('Standard Deviation COVID-19 & Pneumonia Deaths for Ages 65 and up: ' + str(ag_65_up_covid_and_pneumonia_deaths_std))